name: mink_utils
description: A collection of helper functions mainly for woking with iterables and time
version: 1.0.1
homepage: https://github.com/minktec/mink_utils
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  mink_flutter_utils:
    git:
      url: git@github.com:MinkTec/mink_utils.git
      ref: HEAD
      path: packages/mink_flutter_utils

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  melos: ^3.4.0
  test: ^1.24.9
  custom_lint: any
  minklint: any
