name: mink_utils
description: A collection of helper functions mainly for woking with iterables and time
version: 1.0.1
homepage: https://github.com/minktec/mink_utils

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.1
  collection: ^1.17.0
  quiver: ^3.2.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  json_annotation: ^4.8.0
  path_provider: ^2.0.13
  xdg_directories: any
  archive: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
