name: mink_flutter_utils
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  mink_dart_utils:
    git:
      url: git@github.com:MinkTec/mink_utils.git
      ref: HEAD
      path: packages/mink_dart_utils
  path_provider: ^2.1.1
  xdg_directories: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
